-- AlterTable
ALTER TABLE "Book" ADD COLUMN     "className" TEXT,
ADD COLUMN     "type" TEXT NOT NULL DEFAULT 'EDUCATION_BOOK',
ALTER COLUMN "subject" DROP NOT NULL,
ALTER COLUMN "level" DROP NOT NULL;
